language: objective-c
osx_image: xcode9.4

cache:
  directories:
  - Carthage

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty

before_script:
  # Build dependencies(only build)
  # - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
  # When adding new dependencies or want to download latest versions
  - carthage update --cache-builds
  # explanation for bootstrap vs update: https://github.com/Carthage/Carthage/issues/848

script:
  - set -o pipefail && xcodebuild -project KataLogInLogOut.xcodeproj -scheme 'KataLogInLogOut' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
